export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_VIEW_REQUEST = 'PRODUCT_VIEW_REQUEST';
export const PRODUCT_VIEW_SUCCESS = 'PRODUCT_VIEW_SUCCESS';
export const PRODUCT_VIEW_FAIL = 'PRODUCT_VIEW_FAIL';
